### ISSUE TITLE
feat: Support for custom styles

### ISSUE THREAD

**Issue by simsrw73** [walles/moar#112]
Would it be possible to support custom styles? I was looking for a Catppuccin style/them but don't see it listed. Looking at Chroma, I do see it (in its four variations) listed: https://github.com/alecthomas/chroma/tree/master/styles. The docs don't mention a config file or flag to read style. Is this possible or could it be added?

**Comment by walles** [comment]
Hello Randy!

I just released `moar` `v1.11.2` which adds support for `--style catppuccin-mocha`.

Is this good enough to close this ticket? I know it's not exactly what you asked for, but if it's just catppuccin you're after this should be it.

**Comment by simsrw73** [comment]
Thank you! This does everything I need. But does not seem to be fully integrated. It works if I set the MOAR env variable, but I couldn't get it to work on the command line (`.\moar-v1.11.2-windows-amd64.exe --style "catppucin mocha" .\.config\pwsh\profile.ps1`). Also, the link displayed by `moar --help` ([https://xyproto.github.io/splash/docs/longer/all.html](https://xyproto.github.io/splash/docs/longer/all.html)) does not show the new themes.

**Comment by walles** [comment]
The style has to be with a dash, not a space: `catppuccin-mocha`

Specifically it has to match the text at the top of the style XML in Chroma:
https://github.com/alecthomas/chroma/blob/45e3bfb671684372414f2ba3ed45439cc0193664/styles/catppuccin-mocha.xml#L1

Regarding the `--help` link, the catppuccin styles were added to Chroma in October, and the gallery pages haven't been updated since June. Bug filed: https://github.com/alecthomas/chroma/issues/719

**Comment by simsrw73** [comment]
Ahh, sorry, I thought I had tried that. Works great. Thanks for the quick fix. And thanks for moar! Terrific pager.
