### ISSUE TITLE
ct moar | wc hangs

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#176]
mo = "ct moar" and then if run mo <file_name> and pipe anything to this example mo <file_name> | wc ..it freeze the cli or tab and ctrl + c/z/d nothing works ..... Request you please address this scenario also and in any freeze case ctrl + c/z should work

**Comment by walles** [comment]
It seems that `ct` tells `moar` that `stdout` is a terminal even when it isn't (`ct moar xxx | wc`).

This would be an issue with `ct`, and I suggest you open a ticket with the `ct` developers.

# Longer Explanation

When `moar` starts it early on decides whether it's printing to a terminal or a stream.

It does this by doing `isatty()` ("is this a terminal?") on `stdout`.

If `isatty()` says "terminal" then `moar` shows its UI.

Enter `ct`. `ct` seems to be telling `moar` that `stdout` is a terminal, even in the `ct moar | wc` case.

## Workaround(ish)

Press `q`. Since `moar` believes it's printing to a terminal, it will respond to keypresses.

Note that the word counts will be for `moar`'s UI in this case, and not for the input file which is what you might expect. Try with `cat` to see what I mean.
