### ISSUE TITLE
Allow inversion of no-xxx flags.

### ISSUE THREAD

**Issue by eode** [walles/moar#197]
Sometimes, as with line numbering in my case, i want line numbering off by default, but to add it when needed. 

Turning it off by default is simple enough, but turning it back on isn't easily apparent.

What I'd like:
* accept `xxxx` versions of all `no-xxxx` flags
* last argument wins

So that if `moar` is aliased to, for example, `moar -no-linenumbers`, then it's simple enough to just type `moar -linenumbers` and get linenumbers -- though the underlying command moar is receiving is `moar -no-linenumbers -linenumbers`

I think this is an elegant solution because:
* it doesn't interfere with any defaults or user expectations
* it is a common enough design pattern to be easily intuited

Thanks for making the world moar nice.  Before if found this program, I had less.

**Comment by walles** [comment]
As a workaround (not a fix), pressing <kbd><-</kbd> (left arrow key) when inside of `moar` will get you line numbers.

Obvious to me because I wrote it, not sure how obvious it is for anybody else :).

**Comment by walles** [comment]
Even if I agree your request makes sense, AFAICT [`flag`](https://pkg.go.dev/flag) from the standard library (which is what I'm using for command line parsing) doesn't support what you're after.

And adding a separate `-linenumbers` option wouldn't work either, because `flag` hides from me the order in which the command line arguments showed up.

So it seems this would involve quite some work, including replacing the command line parser.

How do you feel about the press-left-arrow-key solution?

**Comment by walles** [comment]
Another (not super great) workaround is to specify `--no-linenumbers=false`.

**Comment by eode** [comment]
Ah, yeah..  I know the 'underlying lib doesn't support this' problem.  :-)

It's such an issue that I'd do a rework myself if it were my tool.   Switching line numbers on and off with the hotkey works well enough for me.

As far as I'm concerned, you can close this.
