### ISSUE TITLE
Advantages over bat?

### ISSUE THREAD

**Issue by CarterLi** [walles/moar#236]
I am a bat user and just found this. Should I switch?

**Comment by walles** [comment]
You should try and see what you think! Since switching in either direction is super simple, Just Do It™.

That said, since `bat` is a wrapper around `less`, you actually have three options here:
1. Use `moar` instead of `bat`
2. Tell `bat` to use `moar` as its pager (`export PAGER=moar` or `set -Ux PAGER moar` in [`fish`](https://fishshell.com/))
3. Stay with `bat`

If you ever search, you should probably go with 1 or 2 since search in `less` is bad (IMO, that's why I started `moar` in the first place).

If you're having problems with mouse scrolling you may want to go with 1 or 2 since it can sometimes be tricky to get right in `less`.

If you switch entirely you'll probably see some differences in syntax highlighting, since `moar` and `bat` use different highlighters.

I'm rambling, was any of this helpful?

If you did try it, let me know your reactions!

**Comment by CarterLi** [comment]
Found a bug of syntax highlighting

Try `#define TEST "//test"`

**Comment by walles** [comment]
`moar` is using Chroma for syntax highlighting.

I found what I believe is this issue already reported, and added your test case there:
https://github.com/alecthomas/chroma/issues/953#issuecomment-2282661521

**Comment by CarterLi** [comment]
The syntax highlighting of moar is really bad.

![image](https://github.com/user-attachments/assets/65063ad3-2554-4e4a-b8fa-c0f5a7617c6c)

Why is the 1st and 3rd `#include` are red but 2nd and 4th `#include` are white?

bat:

![image](https://github.com/user-attachments/assets/e587f343-c19f-4599-86ee-937934c30c01)

I don't think I want to change at this time. Thanks.

**Comment by CarterLi** [comment]
> `moar` is using Chroma for syntax highlighting.

Well I don't use Chroma. I use moar.

**Comment by walles** [comment]
The sucky includes highlighting is fixed now in v1.25.4:

https://github.com/walles/moar/releases/tag/v1.25.4

**Comment by texastoland** [comment]
Randomly stumbled on this issue. I love Moar! Thanks for your patience and good vibes 🤘🏼
