### ISSUE TITLE
moar breaks hyperlink generated by delta in `git show` on Windows

### ISSUE THREAD

**Issue by CarterLi** [walles/moar#244]
![image](https://github.com/user-attachments/assets/5bf4ccdf-2318-4c5d-8f71-2eab1225de61)

It works if I use `less`

![image](https://github.com/user-attachments/assets/5681730d-1ffb-4826-ac6e-ace8451405f9)

---

It does work for git log

![image](https://github.com/user-attachments/assets/8c60ef94-ae9c-4012-9b2d-601c880e8952)

Clicking the commit hash correctly opens the github page

**Comment by walles** [comment]
Instead of just `git show ed22dd8`, can you do `MOAR=--trace git show ed22dd8`?

That should make `moar` output debug information after exit.

Please post that output here!

**Comment by walles** [comment]
NVM, I found it.

https://github.com/walles/moar/blob/6d3bf3dfd4989abff2f423e5b79994c1a2872e2f/m/textstyles/styledStringSplitter.go#L211-L213

Formally those hyperlinks are invalid, since `\` is not allowed:
https://www.rfc-editor.org/rfc/rfc3986#section-2.3

But since this works with `less`, I will make a change to allow them in `moar`.

**Comment by walles** [comment]
Just released v1.27.1, where these URLs should now be accepted by `moar`:

<https://github.com/walles/moar/releases/tag/v1.27.1>

**Comment by walles** [comment]
Out of curiosity, do you usually click the links generated by Delta?

I like that they are there, but do you ever actually click them @CarterLi?

**Comment by CarterLi** [comment]
Sure
