### ISSUE TITLE
Wrapping long words eats up one character

### ISSUE THREAD

**Issue by lapo-luchini** [walles/moar#250]
```
% seq -s '' 100 199 | moar -wrap
  1 10010110210310410510610710810911011111211311411511611711811912012112212312412512612712812913013113213
    13413513613713813914014114214314414514614714814915015115215315415515615715815916016116216316416516616
    168169170171172173174175176177178179180181182183184185186187188189190191192193194195196197198199
---
```

First line ends with "130 131 132 13[3]" second line starts with "134 135".

Also with different terminal width, still skipping last char on each line:
```
  1 1001011021031041051061071081091101111121131141151161171181191     0121122123124125126127128129130131132133134135136137138139140     4114214314414514614714814915015115215315415515615715815916016     1621631641651661671681691701711721731741751761771781791801811     2183184185186187188189190191192193194195196197198199
---
```

**Comment by walles** [comment]
I failed to repro this with `moar v1.27.2` and iTerm2 3.5.5 (see below).

1. What does `moar --version` say?
2. What terminal program are you using? Does it repro if you try some other terminal?

<img width="864" alt="Skärmavbild 2024-10-09 kl  06 58 16" src="https://github.com/user-attachments/assets/452f99da-7990-4b9c-9ca3-baacae9246de">

**Comment by lapo-luchini** [comment]
I was using `v1.27.0` but upgrading to `.2` doesn't solve it.
I'm using Windows Terminal, which is usually a good terminal (at least, I never had problems with `tmux` and `mosh`), but I now noticed that the rightmost three columns are completely black.
This is with `seq -s '-' 10 99 | moar -wrap` (which is more readable):
![image](https://github.com/user-attachments/assets/45bfd14f-bd3d-4abe-9728-5b226fa6ef54)
opening it inside `tmux` solves the problem while still having two black columns… I guess those are the culprit:
![image](https://github.com/user-attachments/assets/90714a24-569c-4e62-b716-7ffd92a9a0e1)

**Comment by lapo-luchini** [comment]
Ok, no, the blank columns/line seems to be [because of HiDPI scaling](https://github.com/microsoft/terminal/issues/4175), but the "missing letters column" (which goes away inside `tmux`) is I guess a separate issue. 🤔

**Comment by walles** [comment]
To rule out Windows specific issues in `moar`, would it be possible for you to try this with some other terminal app on Windows?

That would tell us whether this is:
1. `moar` doing something strange on WIndows
2. Windows Terminal doing something strange with `moar`'s printouts

I have tried this (on macOS) and it works in:
* iTerm2
* macOS Terminal
* Hyper
* KiTTY
* WezTerm

Unfortunately [Windows Terminal requires Windows](https://github.com/microsoft/terminal?tab=readme-ov-file#installing-and-running-windows-terminal), and since I'm on macOS that makes this tricky for me to troubleshoot.

**Comment by lapo-luchini** [comment]
I don't have other terminals installed (since Windows Terminal is usually pretty excellent, this one might be the first bug I encounter) but I tried using [portable MobaXTerm](https://mobaxterm.mobatek.net/download-home-edition.html) and it works fine:
![image](https://github.com/user-attachments/assets/a9ce21a0-e6db-447f-a92e-d8cb92be4d8f)

Using Windows Terminal I got the same exact bug (last column not showing) in both WSL Ubuntu and Windows native version, both using `moar v1.27.2`.

**Comment by lapo-luchini** [comment]
It also happens to me inside the terminal embedded in Microsoft VS Code.
Which is available on Linux/FreeBSD and maybe macOS (?).

**Comment by lapo-luchini** [comment]
I tried getting terminal size [as suggested here](https://stackoverflow.com/a/74432616/166524) and I got the same width in both `tmux` or raw Windows Terminal.

Raw Windows Terminal:
```sh
% print "\033[9999;9999H\033[6n"
^[[50;106R
```

Inside `tmux`:
```sh
% print "\033[9999;9999H\033[6n"
^[[49;106R
```
(the difference is only vertical due to the status line)

**Comment by lapo-luchini** [comment]
I will report there. 👍🏼
In meantime I tried to reproduce using VSCode on Linux… no bug there. So yes it seems to be Windows-specific.

**Comment by walles** [comment]
I believe this is related to how to write the last character of a screen line.

If this was `moar` getting the size wrong, the wrap would be early rather than missing a character.

Also, since `tmux` manages to write there, it is possible, I just need to know how.

If you have a Go setup and want to experiment, the below function might be a good place to start.

Maybe it should be just `\n` at line ends? Maybe we should skip `\r\n` entirely if the line is as wide as the screen?

https://github.com/walles/moar/blob/d5f1cbd43d83c9e40347f6ef95665dbd72a65ac0/twin/screen.go#L747-L778

**Comment by lapo-luchini** [comment]
> If you have a Go setup and want to experiment, the below function might be a good place to start.

I will gladly try. (I know very little Go, but enough to try)

**Comment by lapo-luchini** [comment]
(I did try a bit, no good result so far.)

**Comment by lapo-luchini** [comment]
I also tried `conhost` (the old Windows temrinal)… which produces an "opposite" but similar result… 🤔
![image](https://github.com/user-attachments/assets/c6a7051d-e8a5-4621-85a4-fc2833923260)

**Comment by walles** [comment]
This should now be fixed in just-released v1.27.3.

If you could try it out and report back @lapo-luchini that would be super!

**Comment by lapo-luchini** [comment]
Wow, I read the other issue and… what an informative ride! 💙
![image](https://github.com/user-attachments/assets/6cb53975-cf80-4a6d-a297-90a91c65cc2d)

**Comment by walles** [comment]
Thanks for driving this to its conclusion @lapo-luchini!
