### ISSUE TITLE
How to search from current line like vim or less ?

### ISSUE THREAD

**Issue by mingwiki** [walles/moar#257]
if type "/something", will always search from beginning. it's not same like vim or less.

for example, I use moar to view my logs. I'd like to search by date first, and search something from the date, moar will always search from the top, not works like vim.

**Comment by walles** [comment]
> if type "/something", will always search from beginning. it's not same like vim or less.

Not exactly.

Just like in VSCode or Firefox, `moar` will search from the current location.

But if there are no hits below the current location, `moar` will wrap and search the remaining part of the file as well.

> for example, I use moar to view my logs. I'd like to search by date first, and search something from the date, moar will always search from the top, not works like vim.

With 02a6f11, ESC while searching will take you back to where the search started. RETURN will stop searching but remain in place.

Not exactly what you asked for, but if `moar` finds something in the wrong part of the file, you can now ESC your way back.

Or since `moar` does regex, you could search for `2024-05-06.*monkeys` to find all monkeys that day.
