### ISSUE TITLE
Mouse select does not work

### ISSUE THREAD

**Issue by 89z** [walles/moar#51]
Using this program:

~~~go
package main

import (
   "github.com/walles/moar/m"
   "strings"
)

func main() {
   s := strings.Repeat("Moar\n", 99)
   r := m.NewReaderFromText("Moar", s)
   m.NewPager(r).Page()
}
~~~

Once the pager starts, I can no longer select any text with my mouse, until I exit the pager.

**Comment by 89z** [comment]
Looks like problem is related to Twin. As a workaround, you can use last Tcell version:

https://github.com/walles/moar/commit/44a064c02487d5c9de5721f6cb9d7c31724d3ec8

**Comment by 89z** [comment]
Looks like problem is related to Twin. As a workaround, you can use last Tcell version:

https://github.com/walles/moar/commit/44a064c02487d5c9de5721f6cb9d7c31724d3ec8

However, it seems Tcell has its own problem regarding mouse select as well.

**Comment by walles** [comment]
For me, to do mouse select I've always had to hold shift / alt / cmd together with the mouse button to be able to select, both with `twin` and with `tcell`.

Being able to experiment with this was one of the multiple reasons I choose to replace `tcell`.

Right now I know of these options:
1. [I request mouse events from the terminal using `\x1b[?1006;1000h`](https://github.com/walles/moar/blob/86ae632f14c2a40112162337605b94b24f0cb12b/twin/screen.go#L168-L174). This gives me mouse scroll wheel events (good) but messes up mouse selection (bad).
2. I don't request any mouse events from the terminal. This makes the mouse scroll wheel not work, or require special terminal settings to work and then work badly, but doesn't mess up mouse selection.
3. Do whatever it is that `less` does, since they have both mouse selection and scroll wheel events at the same time.
4. Implement my own mark / copy given mouse events. Sounds harder than 3 for not much more gain.
5. ...?

**Comment by 89z** [comment]
I think I found a solution for this. We can remove `DeInit`, and just implement `WriteOriginal` like is done with Ov. Here is an example:

~~~go
package m
import "github.com/walles/moar/twin"

func (p *Pager) Page() error {
   screen, e := twin.NewScreen()
   if e != nil { return e }
   p.StartPaging(screen)
   screen.Close()
   for n := 1; n <= p.reader.GetLineCount(); n++ {
      println(p.reader.GetLine(n).Plain())
   }
   return nil
}
~~~

Although this discards any coloring in the original input. Do you know how to deal with that?

**Comment by 89z** [comment]
https://github.com/walles/moar/pull/52

**Comment by 89z** [comment]
Can we reopen this? #52 is helpful, but its not really the same issue. Shift allows me to begin a selection, but then I cant change the start of the selected text, only the end.

**Comment by 89z** [comment]
https://github.com/microsoft/terminal/issues/9933

**Comment by 89z** [comment]
im going to reopen this, as I am no longer happy with the workaround

**Comment by 89z** [comment]
I figured it out for Windows.

You can use Shift to make a selection. If you click the wrong initial spot, you can clear the selection with Esc. Just be careful, if you hit Esc without a selection, the pager will exit.

**Comment by 89z** [comment]
https://github.com/walles/moar/issues/51
https://github.com/walles/moar/issues/53
https://github.com/walles/moar/issues/69
