### ISSUE TITLE
syntax highlighting unreadable on light background

### ISSUE THREAD

**Issue by plgruener** [walles/moar#60]
Moar seems to hardcode some (but not all) of its colors. For example a light grey is used for variables and function arguments, but this is almost invisible when using a light background color. Not all Terminals have white font on black background.

Easy-ish solution: **don't** use hardcoded rgb- or 256-color values anywhere, exclusively use one of the 16 colors set by the terminal. This ensures moar's colors change accordingly when the terminal's colorscheme changes.

(Note: I know dealing with syntax highlighting and colorschemes is hard, especially if you want to support a growing number of programming languages and user-customizable colorschemes (with more than 16colors). I could possibly write you a little summary on how to deal with this, if you're interested.)

**Comment by walles** [comment]
`moar` uses Chroma, which has a sizable number of themes:
<https://xyproto.github.io/splash/docs/longer/all.html>

I think the correct solution here would be to:
1. Add a `-theme=paraiso-light` command line option
2. On startup, pick command line options from a `MOAR` environment variable

If you got that, do you think your problem would be solved?

**Comment by walles** [comment]
Cool, thanks for the info!

FWIW, `moar`'s own UI only uses default foreground and default background colors, so that's why the status bar and the line numbers are red.

Source code coloring on the other hand is done by Chroma in RGB.

How about this then?

* `moar` gets a `-colors=8` flag that tells Chroma to use only 8 colors. Valid values would be `8`, `16` or `256`, or `16M`. Not sure yet what the default should be but let's take that later.
* Again, configurable using the `MOAR` environment variable.

Ref: <https://github.com/alecthomas/chroma/blob/2bcdf19ee22749d0c060f7fb538c1e8c5b2f4715/formatters/tty_indexed.go#L262-L282>

**Comment by walles** [comment]
@plgruener I implemented the solution in <https://github.com/walles/moar/issues/60#issuecomment-839441554>.

In your case, doing `export MOAR="-colors=16"` in some init script before invoking `moar` that should get you the behaviour you want.

If this does *not* help, feel free to comment / reopen.
