### ISSUE TITLE
History

### ISSUE THREAD

**Issue by 89z** [walles/moar#77]
If I do a search, then exit the pager, then start pager again, I have to manually redo the previous search.

Less has `$HOME/.lesshst` or `$env:USERPROFILE\_lesshst`, does Moar have something like that?

**Comment by walles** [comment]
I did think about search history, but decided at that time that it wasn't as needed as in `less`.

In `less` you have to type a lot more to find what you're looking for since the search isn't incremental. And that makes the history feature more important.

In `moar` you have to type less to find what you want, which makes history less important.

**Comment by 89z** [comment]
Closing this now.

For a long time, I was outputting formatted data from SQLite to the console, using Moar to improve the experience. However I think I have gone as far as I can with that approach, so I have switched to using a local server with `html/template` [1]. I appreciate all the help over this time, but I will probably not use Moar any longer. Thanks again.

https://godocs.io/html/template

**Comment by walles** [comment]
Cool, thanks for the PRs!
